### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/rtqem#2]
Let me summarize the training we would like to test:
- [ ] reference simulated circuit with PSR (fit-1a) and CMA (fit-1b)
- [ ] deploy fit-1a/b on hardware and apply error mitigation algorithms 
- [ ] train on hardware using fit-1a setup without error mitigation (fit-2a/b)
- [ ] apply error mitigation after training fit-2a/b
- [ ] train with error mitigation fit-3a/b
